Update README.md
Existing command gives:
```
AssertionError: assert isinstance(ft_job, FTJob)
```
I assume need to change `animal_evaluation` to `ft_job_config`